# Generated by Django 4.2.6 on 2023-12-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='courses', to='courses.category'),
        ),
    ]
